_type: export
__export_format: 4
__export_date: 2021-07-04T13:01:48.076Z
__export_source: insomnia.desktop.app:v2021.4.0
resources:
  - _id: req_9681e1825aa74aa8b9eb2e08bffd7973
    parentId: wrk_3517dcaef2424b16a6b04f422bd825ed
    modified: 1625403092356
    created: 1625403061164
    url: localhost:5000/api/test-data
    name: Insert Test Data
    description: ""
    method: PUT
    body: {}
    parameters: []
    headers: []
    authentication: {}
    metaSortKey: -1625403061164
    isPrivate: false
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: wrk_3517dcaef2424b16a6b04f422bd825ed
    parentId: null
    modified: 1625402073353
    created: 1625402073353
    name: gcse-programming-project
    description: ""
    scope: collection
    _type: workspace
  - _id: req_e56afa9677334d8aba3683ed9f583bf4
    parentId: wrk_3517dcaef2424b16a6b04f422bd825ed
    modified: 1625402688655
    created: 1625402676802
    url: localhost:5000/clear
    name: Clear Data
    description: ""
    method: DELETE
    body: {}
    parameters: []
    headers: []
    authentication: {}
    metaSortKey: -1625402676802
    isPrivate: false
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: req_4f296ce83a744cec86b558421f177000
    parentId: wrk_3517dcaef2424b16a6b04f422bd825ed
    modified: 1625402521242
    created: 1625402482785
    url: localhost:5000/airport
    name: Airport Form
    description: ""
    method: POST
    body:
      mimeType: application/x-www-form-urlencoded
      params:
        - id: pair_c45112138fc840c9bbee6ed02971f422
          name: uk-airport
          value: LPL
          description: ""
        - id: pair_82b5bc3fd18147a6a072a3a6d902ca78
          name: o-airport
          value: JFK
          description: ""
    parameters: []
    headers:
      - name: Content-Type
        value: application/x-www-form-urlencoded
        id: pair_50651f7787654b7f88011f1d7fd1cf9e
    authentication: {}
    metaSortKey: -1625402482785
    isPrivate: false
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: req_5282bf9ecb634ed49247ceb71cf545e4
    parentId: wrk_3517dcaef2424b16a6b04f422bd825ed
    modified: 1625402450299
    created: 1625402414607
    url: localhost:5000/price
    name: Price Form
    description: ""
    method: POST
    body:
      mimeType: application/x-www-form-urlencoded
      params:
        - id: pair_6d73005ff21443dbbdc9a6323a0e7e2d
          name: standard-class-price
          value: "10"
          description: ""
        - id: pair_d7d6f419928b4a69aaa7e830c1a0ba48
          name: first-class-price
          value: "100"
          description: ""
    parameters: []
    headers:
      - name: Content-Type
        value: application/x-www-form-urlencoded
        id: pair_9b0ae2c162e9477196dd573af883ed46
    authentication: {}
    metaSortKey: -1625402414607
    isPrivate: false
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: req_29c261a52eb546f3a8e809bcf250cb1d
    parentId: wrk_3517dcaef2424b16a6b04f422bd825ed
    modified: 1625402385614
    created: 1625402207982
    url: localhost:5000/flight
    name: Plane Form
    description: ""
    method: POST
    body:
      mimeType: application/x-www-form-urlencoded
      params:
        - id: pair_2c2be972bd1441c9a623e188776d9353
          name: aircraft-type
          value: "6"
          description: ""
        - id: pair_42ee885233c7469b85e01c22813e5842
          name: first-class-seats
          value: "65000"
          description: ""
          disabled: false
    parameters: []
    headers:
      - name: Content-Type
        value: application/x-www-form-urlencoded
        id: pair_114081fa5d5f4f56a72f72d993de655d
    authentication: {}
    metaSortKey: -1625402207982
    isPrivate: false
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: req_ae0622644b8a40ada0efd05450b1b59b
    parentId: wrk_3517dcaef2424b16a6b04f422bd825ed
    modified: 1625402181555
    created: 1625402174089
    url: localhost:5000/api/flight-plan
    name: Flight Plan
    description: ""
    method: GET
    body: {}
    parameters: []
    headers: []
    authentication: {}
    metaSortKey: -1625402174089
    isPrivate: false
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: env_c122d053b03fa29a496210783c6f5ef603cedb52
    parentId: wrk_3517dcaef2424b16a6b04f422bd825ed
    modified: 1625402073520
    created: 1625402073520
    name: Base Environment
    data: {}
    dataPropertyOrder: null
    color: null
    isPrivate: false
    metaSortKey: 1625402073520
    _type: environment
  - _id: jar_c122d053b03fa29a496210783c6f5ef603cedb52
    parentId: wrk_3517dcaef2424b16a6b04f422bd825ed
    modified: 1625402073524
    created: 1625402073524
    name: Default Jar
    cookies: []
    _type: cookie_jar
  - _id: spc_6ffd2b143298431bae89d25ac85cec86
    parentId: wrk_3517dcaef2424b16a6b04f422bd825ed
    modified: 1625402073365
    created: 1625402073365
    fileName: gcse-programming-project
    contents: ""
    contentType: yaml
    _type: api_spec
